start: shellcheck the script & apply proposed improvements

diff --git a/start b/start
--- a/start
+++ b/start
@@ -42,32 +42,35 @@ parse_args () {
 check_files_dont_exist () {
     if [ -e WORKSPACE ] || [ -e BUILD ] || [ -e BazelExample.hs ]
     then
-        echo "Current directory already has WORKSPACE and/or BUILD and/or BazelExample.hs files." >/dev/stderr
+        echo "Current directory already has WORKSPACE and/or BUILD and/or BazelExample.hs files." >&2
         exit 1
     fi
 }
 
 check_bazel_version () {
-    local actual_raw=$(bazel version | egrep '^Build label:' | egrep -o '[0-9.]+')
+    actual_raw=$(bazel version | grep -E '^Build label:' | grep -E -o '[0-9.]+')
 
-    IFS=. read actual_major actual_minor actual_patch <<EOF
+    # shellcheck disable=SC2034
+    IFS=. read -r actual_major actual_minor actual_patch <<EOF
 $actual_raw
 EOF
 
-    local expected_min=$MIN_BAZEL_MAJOR.$MIN_BAZEL_MINOR.0
-    local expected_max=$MAX_BAZEL_MAJOR.$MAX_BAZEL_MINOR.x
+    expected_min=$MIN_BAZEL_MAJOR.$MIN_BAZEL_MINOR.0
+    expected_max=$MAX_BAZEL_MAJOR.$MAX_BAZEL_MINOR.x
 
-    if [ "$actual_major" -gt "$MAX_BAZEL_MAJOR" ] || (
+    if [ "$actual_major" -gt "$MAX_BAZEL_MAJOR" ] || {
         [ "$actual_major" -eq "$MAX_BAZEL_MAJOR" ] &&
-            [ "$actual_minor" -gt "$MAX_BAZEL_MINOR" ] )
+            [ "$actual_minor" -gt "$MAX_BAZEL_MINOR" ]
+         }
     then
-	      echo "Warning: a too new version of Bazel detected: v${actual_raw}."  >/dev/stderr
-	      echo "         Recommended versions are from v${expected_min} to v${expected_max}."  >/dev/stderr
-    elif [ "$actual_major" -lt "$MIN_BAZEL_MAJOR" ] || (
+	      echo "Warning: a too new version of Bazel detected: v${actual_raw}."  >&2
+	      echo "         Recommended versions are from v${expected_min} to v${expected_max}."  >&2
+    elif [ "$actual_major" -lt "$MIN_BAZEL_MAJOR" ] || {
           [ "$actual_major" -eq "$MIN_BAZEL_MAJOR" ] &&
-            [ "$actual_minor" -lt "$MIN_BAZEL_MINOR" ] )
+            [ "$actual_minor" -lt "$MIN_BAZEL_MINOR" ]
+         }
     then
-        echo "Error: Need at least Bazel v${expected_min} but v${actual_raw} detected." >/dev/stderr
+        echo "Error: Need at least Bazel v${expected_min} but v${actual_raw} detected." >&2
         exit 1
     fi
 }
