DEBUG

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -1,9 +1,9 @@
 name: Continuous integration
 on:
   push:
-    branches: master
-  pull_request:
-    branches: master
+  #   branches: master
+  # pull_request:
+  #   branches: master
   workflow_dispatch: # allows manual triggering
   schedule:
     - cron: '1 11 * * *'
@@ -16,141 +16,141 @@ concurrency:
   cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
 
 jobs:
-  lint:
-    name: Format & Lint
-    runs-on: ubuntu-24.04
-    steps:
-      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-      - uses: tweag/configure-bazel-remote-cache-auth@144b0b915f13a418f5eafe2f68d19564ec136c62 # v0.1.1
-        with:
-          buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
-          bazelrc_path: .bazelrc.auth
-      - uses: ./.github/actions/set_tcp_keepalive_time
-      - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3
-        with:
-          machine: api.github.com
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Configure
-        run: |
-          cat >>.bazelrc.local <<EOF
-          common --config=ci
-          EOF
-      - run: |
-          bazelisk test buildifier:buildifier_test
+  # lint:
+  #   name: Format & Lint
+  #   runs-on: ubuntu-24.04
+  #   steps:
+  #     - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+  #     - uses: tweag/configure-bazel-remote-cache-auth@144b0b915f13a418f5eafe2f68d19564ec136c62 # v0.1.1
+  #       with:
+  #         buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
+  #         bazelrc_path: .bazelrc.auth
+  #     - uses: ./.github/actions/set_tcp_keepalive_time
+  #     - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3
+  #       with:
+  #         machine: api.github.com
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Configure
+  #       run: |
+  #         cat >>.bazelrc.local <<EOF
+  #         common --config=ci
+  #         EOF
+  #     - run: |
+  #         bazelisk test buildifier:buildifier_test
 
-  test-nixpkgs:
-    name: Build & Test - Nixpkgs
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-24.04, macos-14]
-        module: [rules_haskell, rules_haskell_nix, rules_haskell_tests]
-        bzlmod: [true, false]
-        ghc:
-          - 9.4.8
-          - 9.6.5
-          - 9.8.2
-          - 9.10.3
-        exclude:
-          - module: rules_haskell_nix
+  # test-nixpkgs:
+  #   name: Build & Test - Nixpkgs
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ubuntu-24.04, macos-14]
+  #       module: [rules_haskell, rules_haskell_nix, rules_haskell_tests]
+  #       bzlmod: [true, false]
+  #       ghc:
+  #         - 9.4.8
+  #         - 9.6.5
+  #         - 9.8.2
+  #         - 9.10.3
+  #       exclude:
+  #         - module: rules_haskell_nix
 
-            bzlmod: false
-          # TODO: in a MODULE.bazel file we declare version specific dependencies, would need to use stack snapshot json
-          #       and stack config per GHC version
-          - ghc: 9.8.2
-            bzlmod: true
-          - ghc: 9.6.5
-            bzlmod: true
-          - ghc: 9.10.3
-            bzlmod: true
-          # GHC 9.10.3 not available in current nixpkgs pin (2024-07-02)
-          - ghc: 9.10.3
-            os: ubuntu-24.04
-          - ghc: 9.10.3
-            os: macos-14
-    runs-on: ${{ matrix.os }}
-    env:
-      NIX_SHELL_ARGS: --arg docTools false --argstr ghcVersion ${{ matrix.ghc }}
-    steps:
-      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-      - uses: ./.github/actions/free_disk_space_on_linux
-      - name: Mount Bazel cache
-        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
-        with:
-          path: ~/repo-cache
-          key: repo-cache-${{ runner.os }}-nixpkgs-${{ env.cache-version }}
-      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
-        with:
-          nix_path: nixpkgs=./nixpkgs/default.nix
-          extra_nix_config: |
-            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
-            extra-substituters = https://cache.iog.io
-      - uses: tweag/configure-bazel-remote-cache-auth@144b0b915f13a418f5eafe2f68d19564ec136c62 # v0.1.1
-        with:
-          buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
-          bazelrc_path: .bazelrc.auth
-      - uses: ./.github/actions/set_tcp_keepalive_time
-      - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3
-        with:
-          machine: api.github.com
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Configure
-        run: |
-          case ${{ runner.os }} in
-            macOS) BUILD_CONFIG=macos-nixpkgs;;
-            Linux) BUILD_CONFIG=linux-nixpkgs;;
-          esac
-          cat >>.bazelrc.local <<EOF
-          common --config=ci
-          build --config=$BUILD_CONFIG
-          common --enable_bzlmod=${{ matrix.bzlmod }}
-          EOF
-          cp .bazelrc.local rules_haskell_nix
-          cp .bazelrc.local rules_haskell_tests
-      - name: Build & test - rules_haskell
-        if: matrix.module == 'rules_haskell'
-        uses: tweag/run-nix-shell@5d825ec7e0038b6c613f14d523203a2ea49abddb # v0.3.0
-        with:
-          options: ${{ env.NIX_SHELL_ARGS }}
-          run: |
-            bazel test //...
-            bazel build //docs:api_html
-            bazel build //docs:guide_html
-      - name: Build & test - rules_haskell_nix
-        if: matrix.module == 'rules_haskell_nix'
-        uses: tweag/run-nix-shell@5d825ec7e0038b6c613f14d523203a2ea49abddb # v0.3.0
-        with:
-          derivation-path: .
-          options: -I nixpkgs=../nixpkgs/default.nix ${{ env.NIX_SHELL_ARGS }}
-          working-directory: rules_haskell_nix
-          run: bazel test //...
-      - name: Build & test - rules_haskell_tests
-        if: matrix.module == 'rules_haskell_tests'
-        uses: tweag/run-nix-shell@5d825ec7e0038b6c613f14d523203a2ea49abddb # v0.3.0
-        with:
-          options: ${{ env.NIX_SHELL_ARGS }}
-          working-directory: rules_haskell_tests
-          run: |
-            # ensure analysis works
-            bazel build --nobuild ... | (echo "targets: $( wc -l )")
-            # XXX run start script `--with-bzlmod=true` when supported
-            if ! ${{ matrix.bzlmod }}; then
-              ./tests/run-start-script.sh --use-nix --with-bzlmod=${{ matrix.bzlmod }}
-            fi
-            bazel build //tests:run-tests
-            # Shutdown Bazel to free up memory
-            # https://github.com/tweag/rules_haskell/issues/2089.
-            bazel shutdown
-            # Execute the tests dumping out memory/process information before and after each test.
-            RHT_PRINT_MEMORY=true ./bazel-ci-bin/tests/run-tests
-            bazel coverage //...
+  #           bzlmod: false
+  #         # TODO: in a MODULE.bazel file we declare version specific dependencies, would need to use stack snapshot json
+  #         #       and stack config per GHC version
+  #         - ghc: 9.8.2
+  #           bzlmod: true
+  #         - ghc: 9.6.5
+  #           bzlmod: true
+  #         - ghc: 9.10.3
+  #           bzlmod: true
+  #         # GHC 9.10.3 not available in current nixpkgs pin (2024-07-02)
+  #         - ghc: 9.10.3
+  #           os: ubuntu-24.04
+  #         - ghc: 9.10.3
+  #           os: macos-14
+  #   runs-on: ${{ matrix.os }}
+  #   env:
+  #     NIX_SHELL_ARGS: --arg docTools false --argstr ghcVersion ${{ matrix.ghc }}
+  #   steps:
+  #     - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+  #     - uses: ./.github/actions/free_disk_space_on_linux
+  #     - name: Mount Bazel cache
+  #       uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
+  #       with:
+  #         path: ~/repo-cache
+  #         key: repo-cache-${{ runner.os }}-nixpkgs-${{ env.cache-version }}
+  #     - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
+  #       with:
+  #         nix_path: nixpkgs=./nixpkgs/default.nix
+  #         extra_nix_config: |
+  #           trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
+  #           extra-substituters = https://cache.iog.io
+  #     - uses: tweag/configure-bazel-remote-cache-auth@144b0b915f13a418f5eafe2f68d19564ec136c62 # v0.1.1
+  #       with:
+  #         buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
+  #         bazelrc_path: .bazelrc.auth
+  #     - uses: ./.github/actions/set_tcp_keepalive_time
+  #     - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3
+  #       with:
+  #         machine: api.github.com
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Configure
+  #       run: |
+  #         case ${{ runner.os }} in
+  #           macOS) BUILD_CONFIG=macos-nixpkgs;;
+  #           Linux) BUILD_CONFIG=linux-nixpkgs;;
+  #         esac
+  #         cat >>.bazelrc.local <<EOF
+  #         common --config=ci
+  #         build --config=$BUILD_CONFIG
+  #         common --enable_bzlmod=${{ matrix.bzlmod }}
+  #         EOF
+  #         cp .bazelrc.local rules_haskell_nix
+  #         cp .bazelrc.local rules_haskell_tests
+  #     - name: Build & test - rules_haskell
+  #       if: matrix.module == 'rules_haskell'
+  #       uses: tweag/run-nix-shell@5d825ec7e0038b6c613f14d523203a2ea49abddb # v0.3.0
+  #       with:
+  #         options: ${{ env.NIX_SHELL_ARGS }}
+  #         run: |
+  #           bazel test //...
+  #           bazel build //docs:api_html
+  #           bazel build //docs:guide_html
+  #     - name: Build & test - rules_haskell_nix
+  #       if: matrix.module == 'rules_haskell_nix'
+  #       uses: tweag/run-nix-shell@5d825ec7e0038b6c613f14d523203a2ea49abddb # v0.3.0
+  #       with:
+  #         derivation-path: .
+  #         options: -I nixpkgs=../nixpkgs/default.nix ${{ env.NIX_SHELL_ARGS }}
+  #         working-directory: rules_haskell_nix
+  #         run: bazel test //...
+  #     - name: Build & test - rules_haskell_tests
+  #       if: matrix.module == 'rules_haskell_tests'
+  #       uses: tweag/run-nix-shell@5d825ec7e0038b6c613f14d523203a2ea49abddb # v0.3.0
+  #       with:
+  #         options: ${{ env.NIX_SHELL_ARGS }}
+  #         working-directory: rules_haskell_tests
+  #         run: |
+  #           # ensure analysis works
+  #           bazel build --nobuild ... | (echo "targets: $( wc -l )")
+  #           # XXX run start script `--with-bzlmod=true` when supported
+  #           if ! ${{ matrix.bzlmod }}; then
+  #             ./tests/run-start-script.sh --use-nix --with-bzlmod=${{ matrix.bzlmod }}
+  #           fi
+  #           bazel build //tests:run-tests
+  #           # Shutdown Bazel to free up memory
+  #           # https://github.com/tweag/rules_haskell/issues/2089.
+  #           bazel shutdown
+  #           # Execute the tests dumping out memory/process information before and after each test.
+  #           RHT_PRINT_MEMORY=true ./bazel-ci-bin/tests/run-tests
+  #           bazel coverage //...
 
   test-bindist:
     name: Build & Test - bindist
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-24.04, macos-14, windows-2022]
+        os: [windows-2022]
         module: [rules_haskell, rules_haskell_tests]
         bzlmod: [true, false]
         ghc:
@@ -231,6 +231,10 @@ jobs:
           # Quote the package specifier so that it works on Windows
           bazelisk test "//..."
 
+      - name: Setup tmate session
+        uses: mxschmitt/action-tmate@v3
+        with:
+          limit-access-to-actor: true
       - name: Build & test - rules_haskell_tests
         if: matrix.module == 'rules_haskell_tests'
         shell: bash
@@ -267,91 +271,91 @@ jobs:
           name: Logs ${{ matrix.os }} ${{ matrix.module }} ${{ matrix.bzlmod }}
           path: logs
 
-  examples-bindist:
-    name: Build & Test Examples - bindist
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-24.04, macos-14, macos-15-intel, windows-2022]
-        bzlmod: [true, false]
-        bazel:
-          - "6.x"
-          - "7.x"
-        exclude:
-          # TODO(cb) add full support for Bazel 7
-          - os: windows-2022
-            bazel: "7.x"
-    env:
-      USE_BAZEL_VERSION: ${{ matrix.bazel }}
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-      - uses: ./.github/actions/free_disk_space_on_linux
-      - name: Mount Bazel cache
-        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
-        with:
-          path: ~/repo-cache
-          key: repo-cache-${{ runner.os }}-bindist-${{ env.cache-version }}
-      - uses: tweag/configure-bazel-remote-cache-auth@144b0b915f13a418f5eafe2f68d19564ec136c62 # v0.1.1
-        with:
-          buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
-          bazelrc_path: .bazelrc.auth
-      - uses: ./.github/actions/set_tcp_keepalive_time
-      - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3
-        with:
-          machine: api.github.com
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Configure
-        shell: bash
-        run: |
-          case "${{ runner.os }}" in
-            macOS) BUILD_CONFIG=macos-bindist;;
-            Linux) BUILD_CONFIG=linux-bindist;;
-            Windows) BUILD_CONFIG=ci-windows-bindist;;
-          esac
-          if [[ ${{ runner.os }} == Windows ]]; then
-              output_root_setting="startup --output_user_root=C:/_bzl"
-              # On windows, we use a separate remote cache for bzlmod,
-              # because the c dependency analysis is leaking absolute paths which are different
-              if ${{ matrix.bzlmod }}; then
-                bzlmod_cache_silo_key='build --remote_default_exec_properties=bzlmod-cache-silo-key=bzlmod'
-              else
-                bzlmod_cache_silo_key='build --remote_default_exec_properties=bzlmod-cache-silo-key=workspace'
-              fi
-          else
-              output_root_setting=""
-              bzlmod_cache_silo_key=""
-          fi
-          cat >>.bazelrc.local <<EOF
-          common --config=ci
-          build --config=$BUILD_CONFIG
-          $output_root_setting
-          $bzlmod_cache_silo_key
-          common --enable_bzlmod=${{ matrix.bzlmod }}
-          EOF
-      - name: Build
-        shell: bash
-        working-directory: examples
-        run: |
-          # Quote the package specifier so that it works on Windows
-          bazelisk build "//..."
+  # examples-bindist:
+  #   name: Build & Test Examples - bindist
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ubuntu-24.04, macos-14, macos-15-intel, windows-2022]
+  #       bzlmod: [true, false]
+  #       bazel:
+  #         - "6.x"
+  #         - "7.x"
+  #       exclude:
+  #         # TODO(cb) add full support for Bazel 7
+  #         - os: windows-2022
+  #           bazel: "7.x"
+  #   env:
+  #     USE_BAZEL_VERSION: ${{ matrix.bazel }}
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #     - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+  #     - uses: ./.github/actions/free_disk_space_on_linux
+  #     - name: Mount Bazel cache
+  #       uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
+  #       with:
+  #         path: ~/repo-cache
+  #         key: repo-cache-${{ runner.os }}-bindist-${{ env.cache-version }}
+  #     - uses: tweag/configure-bazel-remote-cache-auth@144b0b915f13a418f5eafe2f68d19564ec136c62 # v0.1.1
+  #       with:
+  #         buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
+  #         bazelrc_path: .bazelrc.auth
+  #     - uses: ./.github/actions/set_tcp_keepalive_time
+  #     - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3
+  #       with:
+  #         machine: api.github.com
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Configure
+  #       shell: bash
+  #       run: |
+  #         case "${{ runner.os }}" in
+  #           macOS) BUILD_CONFIG=macos-bindist;;
+  #           Linux) BUILD_CONFIG=linux-bindist;;
+  #           Windows) BUILD_CONFIG=ci-windows-bindist;;
+  #         esac
+  #         if [[ ${{ runner.os }} == Windows ]]; then
+  #             output_root_setting="startup --output_user_root=C:/_bzl"
+  #             # On windows, we use a separate remote cache for bzlmod,
+  #             # because the c dependency analysis is leaking absolute paths which are different
+  #             if ${{ matrix.bzlmod }}; then
+  #               bzlmod_cache_silo_key='build --remote_default_exec_properties=bzlmod-cache-silo-key=bzlmod'
+  #             else
+  #               bzlmod_cache_silo_key='build --remote_default_exec_properties=bzlmod-cache-silo-key=workspace'
+  #             fi
+  #         else
+  #             output_root_setting=""
+  #             bzlmod_cache_silo_key=""
+  #         fi
+  #         cat >>.bazelrc.local <<EOF
+  #         common --config=ci
+  #         build --config=$BUILD_CONFIG
+  #         $output_root_setting
+  #         $bzlmod_cache_silo_key
+  #         common --enable_bzlmod=${{ matrix.bzlmod }}
+  #         EOF
+  #     - name: Build
+  #       shell: bash
+  #       working-directory: examples
+  #       run: |
+  #         # Quote the package specifier so that it works on Windows
+  #         bazelisk build "//..."
 
-      - name: Test
-        shell: bash
-        working-directory: examples
-        run: |
-          # Quote the package specifier so that it works on Windows
-          bazelisk test "//..."
+  #     - name: Test
+  #       shell: bash
+  #       working-directory: examples
+  #       run: |
+  #         # Quote the package specifier so that it works on Windows
+  #         bazelisk test "//..."
 
-  all_ci_tests:
-    runs-on: ubuntu-24.04
-    needs:
-      - lint
-      - examples-bindist
-      - test-nixpkgs
-      - test-bindist
-    if: ${{ always() }}
-    steps:
-      - uses: cgrindel/gha_join_jobs@605424defceef3181c9fde3df903ea8ec35e267a # v1
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+  # all_ci_tests:
+  #   runs-on: ubuntu-24.04
+  #   needs:
+  #     - lint
+  #     - examples-bindist
+  #     - test-nixpkgs
+  #     - test-bindist
+  #   if: ${{ always() }}
+  #   steps:
+  #     - uses: cgrindel/gha_join_jobs@605424defceef3181c9fde3df903ea8ec35e267a # v1
+  #       with:
+  #         github_token: ${{ secrets.GITHUB_TOKEN }}
